export const chatConstants = {
	CHANNEL_CREATE: 'CHANNEL_CREATE',
	CHANNEL_CREATE_SUCCESS: 'CHANNEL_CREATE_SUCCESS',
	CHANNEL_SWITCH: 'CHANNEL_SWITCH',
	ADD_CHANNEL_MEMBERS: 'ADD_CHANNEL_MEMBERS',
	ADD_CHANNEL_MEMBERS_SUCCESS: 'ADD_CHANNEL_MEMBERS_SUCCESS',

	MESSAGE_GET: 'MESSAGE_GET',
	MESSAGE_GET_SUCCESS: 'MESSAGE_GET_SUCCESS',

	ERROR_CHANNEL: 'ERROR_CHANNEL',
	ERROR_MESSAGE: 'ERROR_MESSAGE',
};
