export const chatConstants = {
	CHANNEL_CREATE: 'CHANNEL_CREATE',
	CHANNEL_CREATE_SUCCESS: 'CHANNEL_CREATE_SUCCESS',
	CHANNEL_SWITCH: 'CHANNEL_SWITCH',
	JOIN_CHANNEL: 'JOIN_CHANNEL',
	JOIN_CHANNEL_SUCCESS: 'JOIN_CHANNEL_SUCCESS',
	SEARCH_CHANNEL_SUCCESS: 'SEARCH_CHANNEL_SUCCESS',

	MESSAGE_GET: 'MESSAGE_GET',
	MESSAGE_GET_SUCCESS: 'MESSAGE_GET_SUCCESS',

	ERROR_CHANNEL: 'ERROR_CHANNEL',
	ERROR_MESSAGE: 'ERROR_MESSAGE',
};
