export const userConstants = {
	REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
	GET_DETAILS_SUCCESS: 'GET_DETAILS_SUCCESS',
	GET_DETAILS_ERROR: 'GET_DETAILS_ERROR',
	EDIT_SUCCESS: 'EDIT_SUCCESS',
	EDIT_ERROR: 'EDIT_ERROR',
	LOGOUT: 'USERS_LOGOUT',
};
